name: Build and Push Podman Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Podman
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      # Log in to GitHub Packages
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.PAT__TOKEN }}" | podman login ghcr.io -u $GITHUB_ACTOR --password-stdin

      # Build Podman image
      - name: Build Podman image
        run: |
          podman build -t ghcr.io/${{ github.repository }}/yolo_camera_node_ros:latest .

      # Push Podman image to GitHub Packages
      - name: Push Podman image to GitHub Packages
        run: |
          podman push ghcr.io/${{ github.repository }}/yolo_camera_node_ros:latest
