name: Build and Push Multi-Architecture Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up QEMU (potrebné na podporu viac architektúr)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Set up Docker Buildx (na zostavenie multiarchitektúrneho obrazu)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push multi-arch image
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository }}/yolo_camera_node_ros:latest
          push: true
